version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - yum update -y
      - yum install -y mariadb-client mariadb-server libmariadb-dev  # Install MariaDB development headers
      - python -m pip install --upgrade pip setuptools
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build steps"

  build:
    commands:
      - echo "Running build steps"
      - python manage.py migrate
      - python manage.py collectstatic --noinput

  post_build:
    commands:
      - echo "Running post-build steps"

artifacts:
  files: '**/*'
